### PR TITLE
Add support for reading base64-encoded trust bundle from config map

### PR DESCRIPTION
**Pull request by thunderboltsid**
The base64 trust bundle configmap can be provided via both Data as well as BinaryData. The one in ConfigMap.Data is used as-is. The one in ConfigMap.BinaryData is decoded using base64. If the `ca.crt` key is present in both Data and BinaryData, the one in Data takes preference. 

**How was this tested?**
The PR updates the unit test to add a check where the ConfigMap has a base64 encoded cert in `BinaryData` and the resulting trust bundle from `GetManagementEndpoint` method yields the decoded cert. Cert for testing is generated using the `internal/certutils` package added in this PR.

### CODE REVIEW

**Review by yannickstruyf3 — APPROVED** [review]

**Comment by deepakm-ntnx** [comment]
@thunderboltsid as discussed, we need to find out when do the unit test runs in the checks

**Review by deepakm-ntnx — APPROVED** [review]
please also verify if there are negative test cases as well covered by unit tests

**Comment by thunderboltsid** [comment]
> @thunderboltsid as discussed, we need to find out when do the unit test runs in the checks

They are supposed to always run but the action got incorrectly updated in a previous PR and that fails silently. Here's a fix https://github.com/nutanix-cloud-native/prism-go-client/pull/45

**Review by tuxtof — DISMISSED** [review]
LGTM

**Review by tuxtof — APPROVED** [review]

**Pull request merged**
